# Generated by Django 4.0.3 on 2024-01-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0002_alter_books_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
    ]
